# Generated by Django 4.0.3 on 2022-03-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0016_match_admin_alter_match_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_searching', models.BooleanField(default=False)),
                ('is_open_for_match', models.BooleanField(default=False)),
                ('is_visible_on_leaderbord', models.BooleanField(default=True)),
                ('elo_boosts_left', models.IntegerField(default=0)),
                ('ranked_sport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='match.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
