# Generated by Django 4.0.3 on 2022-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('number_of_players', models.IntegerField()),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Lobby'), (2, 'Scheduled'), (3, 'Active'), (4, 'Finished'), (5, 'Canceled')])),
                ('average_elo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_ranked', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
