# Generated by Django 4.0.3 on 2022-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('L', 'Lobby'), ('S', 'Scheduled'), ('A', 'Active'), ('F', 'Finished'), ('C', 'Canceled')], max_length=1),
        ),
    ]
