# Generated by Django 4.0.3 on 2022-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_match_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='match',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('L', 'Lobby'), ('S', 'Scheduled'), ('A', 'Active'), ('F', 'Finished'), ('C', 'Canceled')], default='L', max_length=1),
        ),
    ]
