# Generated by Django 4.0.3 on 2022-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_match_latitude_match_longitude_alter_match_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basketball', max_length=20)),
                ('max_players', models.IntegerField(default=100)),
                ('match_type_options', models.CharField(max_length=100)),
            ],
        ),
    ]
