# Generated by Django 4.0.3 on 2022-03-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_match_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='match.sport'),
        ),
    ]
