# Generated by Django 4.0.3 on 2022-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_match_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='sport',
        ),
    ]
