# Generated by Django 4.0.3 on 2022-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_match_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='match_type_options',
        ),
        migrations.AddField(
            model_name='sport',
            name='min_players',
            field=models.IntegerField(default=1),
        ),
    ]
