# Generated by Django 4.0.3 on 2022-03-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_match_admin_alter_match_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='admin',
        ),
    ]
