# Generated by Django 4.0.3 on 2022-05-04 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0018_match_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='admin',
        ),
        migrations.AddField(
            model_name='match',
            name='admin',
            field=models.ManyToManyField(default=None, related_name='game_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
