# Generated by Django 4.0.3 on 2022-05-04 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0019_remove_match_admin_match_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='admin',
        ),
        migrations.AddField(
            model_name='match',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
