# Generated by Django 4.0.3 on 2022-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_alter_match_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='admin',
        ),
        migrations.AddField(
            model_name='match',
            name='admin_id',
            field=models.IntegerField(default=0),
        ),
    ]
